import { Poppins, Roboto_Mono } from "next/font/google";
import Header from "./components/Header";

import "swiper/scss";
import "swiper/scss/navigation";
import "react-toastify/dist/ReactToastify.min.css";
import "./styles/main.scss";
import Footer from "./components/Footer";
import localFont from "next/font/local";
import Providers from "./features/Providers";
import Cart from "./components/Cart";
import { GoArrowUpRight } from "react-icons/go";
import { ToastContainer } from "react-toastify";

// Font files can be colocated inside of `pages`
const myFont = localFont({ src: "./fonts/Chillax-Variable.woff2" });

export const metadata = {
	title: "...",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${myFont.className} `}>
				<Providers>
					<ToastContainer
						position="bottom-right"
						autoClose={2000}
						hideProgressBar={false}
						newestOnTop={true}
						closeOnClick
						rtl={false}
						draggable
						pauseOnHover={false}
						theme="dark"
					/>
					<Header />
					<main>{children}</main>
					<section className="contact">
						<h4>contact</h4>
						<div>
							<p>Let's make your fashion brand shine</p>
							<button>
								<span>get in touch</span>
								<span className="arrow">
									<GoArrowUpRight />
								</span>
							</button>
						</div>
					</section>
					<Footer />
					<Cart />
				</Providers>
			</body>
		</html>
	);
}
